services:
  frontend1:
    build: .
    container_name: frontend1
    env_file: .env
    environment:
      - PORT=3001
    expose:
      - "3001"
    command: ["node", "server.js"]

  frontend2:
    build: .
    container_name: frontend2
    env_file: .env
    environment:
      - PORT=3002
    expose:
      - "3002"
    command: ["node", "server.js"]

  nginx_load_balancer:
    image: nginx:latest
    container_name: nginx_load_balancer
    depends_on:
      - frontend1
      - frontend2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
